const app = document.querySelector('#app');
const SAVE_KEY = 'escape-game-escape02-v1';
const DIRS = ['FRONT','RIGHT','BACK','LEFT'];
const IMAGES = {staff:{FRONT:'staff-front.webp',RIGHT:'staff-right.webp',BACK:'staff-back.webp',LEFT:'staff-left.webp'},records:{FRONT:'records-front.webp',RIGHT:'records-right.webp',BACK:'records-back.webp',LEFT:'records-left.webp'}};
const roomNames={staff:'スタッフルーム',records:'診療記録室'};
const defaultState=()=>({active:true,room:'staff',direction:'FRONT',message:'……チリン。少し前を歩く咲の方から、金属の小さな音がした記憶が一瞬だけ戻る。',speaker:'悠',inventory:[],selected:null,flags:{memoryCharm:true},modal:null,input:''});
let s=load();
function load(){try{const raw=JSON.parse(localStorage.getItem(SAVE_KEY)||'null');return raw?{...defaultState(),...raw,flags:{...defaultState().flags,...(raw.flags||{})}}:defaultState()}catch{return defaultState()}}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(s))}
function setFlags(x){s.flags={...s.flags,...x}}
function say(t,sp='悠'){s.message=t;s.speaker=sp}
function addItem(id){if(!s.inventory.includes(id))s.inventory.push(id);s.selected=id}
function removeItem(id){s.inventory=s.inventory.filter(x=>x!==id);if(s.selected===id)s.selected=null}
function traces(){return ['fridge','sink','trash','clock','whiteboard'].filter(k=>s.flags[k]).length}
function render(){if(!s.active)return;app.className='game-shell screen-escape02';const img=IMAGES[s.room][s.direction];const inv=s.inventory.map(id=>`<button class="e2-item ${s.selected===id?'selected':''}" data-e2-item="${id}"><small>${id==='staff_id'?'職員証':id==='passage_key'?'スタッフ専用通路の鍵':'管理表'}</small></button>`).join('')||'<p class="e2-empty">所持品なし</p>';const spots=hotspots().map(h=>`<button class="e2-hotspot" data-e2-interact="${h.id}" style="left:${h.x}%;top:${h.y}%;width:${h.w}%;height:${h.h}%" aria-label="${h.label}"><span>${h.label}</span></button>`).join('');app.innerHTML=`<section class="e2-screen"><header class="e2-header"><div><span>CHAPTER 1 / ESCAPE 02</span><strong>${roomNames[s.room]}</strong></div><button data-e2-action="menu">記録</button></header><div class="e2-scene" data-room="${s.room}" data-dir="${s.direction}"><div class="e2-dir">${s.direction}</div>${spots}<button class="e2-turn left" data-e2-action="left">‹</button><button class="e2-turn right" data-e2-action="right">›</button></div><div class="e2-message"><b>${s.speaker||''}</b><p>${s.message}</p></div><div class="e2-inventory">${inv}</div></section>${modal()}`;bind();save()}
function hotspots(){if(s.room==='staff'){if(s.direction==='FRONT')return [{id:'clock',x:48,y:11,w:17,h:18,label:'壁掛け時計'},{id:'corridorDoor',x:7,y:22,w:24,h:63,label:'廊下への扉'}];if(s.direction==='RIGHT')return [{id:'whiteboard',x:7,y:15,w:38,h:32,label:'ホワイトボード'},{id:'roster',x:44,y:14,w:18,h:28,label:'担当表'},{id:'staffLocker',x:64,y:18,w:30,h:65,label:'職員ロッカー'}];if(s.direction==='BACK')return [{id:'fridge',x:5,y:29,w:24,h:53,label:'冷蔵庫'},{id:'sink',x:34,y:28,w:29,h:32,label:'流し台'},{id:'trash',x:70,y:54,w:20,h:28,label:'ゴミ箱'}];return [{id:'pc',x:10,y:28,w:35,h:31,label:'PC'},{id:'recordDoor',x:56,y:18,w:37,h:66,label:'診療記録室'}]}if(s.direction==='FRONT')return [{id:'anonCases',x:8,y:18,w:64,h:52,label:'最近の診療記録'},{id:'entryDoor',x:76,y:19,w:18,h:64,label:'スタッフルームへの扉'}];if(s.direction==='RIGHT')return [{id:'recordCabinet',x:20,y:18,w:62,h:63,label:'鍵付きキャビネット'}];if(s.direction==='BACK')return [{id:'formalShelf',x:6,y:17,w:88,h:65,label:'正式カルテ棚'}];return [{id:'passageDoor',x:55,y:16,w:37,h:68,label:'スタッフ専用通路'},{id:'wallNote',x:12,y:24,w:28,h:29,label:'棚の番号札'}]}
function interact(id){if(id==='clock'){setFlags({clock:true});say('時計は止まっていない。現在時刻とほぼ合っている。……本当に廃院なのか？')}else if(id==='corridorDoor')say('207号室へ戻るより、咲の痕跡を追いたい。先へ進もう。');else if(id==='whiteboard'){setFlags({whiteboard:true});say('2月6日（金）。下に「搬入」「消耗品補充」「処置室2 清掃」。……今日、誰かがここで働いていた。')}else if(id==='roster'){setFlags({roster:true});say('当番表。今日の「記録担当」は STAFF C とある。')}else if(id==='staffLocker'){if(!s.flags.roster)say('どのロッカーを調べるべきか分からない。');else if(!s.flags.staffId){setFlags({staffId:true});addItem('staff_id');say('STAFF C のロッカーから職員証を見つけた。ID: 4721。')}else say('STAFF C のロッカー。もう目ぼしい物はない。')}else if(id==='fridge'){setFlags({fridge:true});say('電源が入っている。中には消費期限の近い飲み物と食品。最近補充されたものだ。')}else if(id==='sink'){setFlags({sink:true});say('流し台はまだ湿っている。乾ききっていない。')}else if(id==='trash'){setFlags({trash:true});say('新しい包装ゴミ。古い埃の上に、今日捨てられたような物が混じっている。')}else if(id==='pc'){if(!s.flags.staffId)say('ログイン画面。職員IDが必要らしい。');else{s.modal='pc';s.input=''}}else if(id==='recordDoor'){if(!s.flags.pcAuthed)say('4桁の電子ロック。暗証番号を直接示すメモはない。');else{s.modal='record';s.input=''}}else if(id==='anonCases'){setFlags({anonCases:true});say('M-04、F-02、M-11……氏名も住所もない。M-11には「銃創・弾片除去」。普通の診療記録とは思えない。')}else if(id==='formalShelf'){setFlags({formalShelf:true});say('こちらには氏名入りの正式カルテが並ぶ。……名前を書けないのではない。「名前を書かない患者」を別に管理している。')}else if(id==='wallNote'){setFlags({cabinetClue:true});say('棚の番号札に M-04 / F-02 / M-11。横に「末尾一桁」と鉛筆書き。4・2・1……。')}else if(id==='recordCabinet'){if(!s.flags.cabinetClue)say('3桁ダイヤル付き。周囲の番号札が手がかりになりそうだ。');else{s.modal='cabinet';s.input=''}}else if(id==='entryDoor'){s.room='staff';s.direction='LEFT';say('スタッフルームへ戻った。')}else if(id==='passageDoor'){if(!s.flags.passageKey)say('施錠されている。専用の鍵が必要だ。');else{removeItem('passage_key');setFlags({cleared:true});s.modal='clear'}}if(traces()>=3&&!s.flags.activeHospital){setFlags({activeHospital:true});say('……違う。ここは廃院じゃない。今も誰かが使っている。')}render()}
function modal(){if(!s.modal)return '';if(s.modal==='clear')return `<div class="e2-modal-bg"><section class="e2-clear"><p>ESCAPE 02</p><h2>CLEAR</h2><strong>スタッフ専用通路が開いた。</strong><span>管理表の最下部には「侵入 2」。自分と咲のことだと、悠は思う。</span><button data-e2-action="close-clear">クリア画面を閉じる</button></section></div>`;let title='',desc='',len=4;if(s.modal==='pc'){title='STAFF PC';desc='職員証のIDを入力'}if(s.modal==='record'){title='診療記録室';desc='PC表示：「記録室認証 = ID末尾2桁 + 当日の日」'}if(s.modal==='cabinet'){title='RECORD CABINET';desc='棚の番号札の末尾一桁を左から';len=3}if(s.modal==='sheet')return `<div class="e2-modal-bg" data-e2-action="close"><section class="e2-detail"><button data-e2-action="close">×</button><p>当日管理表。最下部に赤字で「侵入 2」。</p></section></div>`;const keys=[1,2,3,4,5,6,7,8,9,'消',0,'決定'].map(k=>`<button data-e2-key="${k}">${k}</button>`).join('');return `<div class="e2-modal-bg"><section class="e2-keypad"><button class="e2-x" data-e2-action="close">×</button><p>${title}</p><h2>${desc}</h2><output>${s.input.padEnd(len,'·')}</output><div>${keys}</div></section></div>`}
function submit(){const v=s.input;if(s.modal==='pc'&&v==='4721'){s.modal=null;setFlags({pcAuthed:true});say('ログイン成功。「記録室認証：更新済」「認証規則：ID末尾2桁 + 当日の日」。IDは4721、今日は6日……。')}else if(s.modal==='record'&&v==='2106'){s.modal=null;s.room='records';s.direction='FRONT';say('電子ロックが解除された。……診療記録室。空気がさらに重い。')}else if(s.modal==='cabinet'&&v==='421'){s.modal=null;setFlags({passageKey:true,managementSheet:true});addItem('passage_key');addItem('management_sheet');say('キャビネットが開いた。《スタッフ専用通路の鍵》と当日の《管理表》を手に入れた。管理表の最下部に「侵入 2」。')}else{say('番号が違う。');s.input=''}render()}
function bind(){app.querySelectorAll('[data-e2-action]').forEach(el=>el.addEventListener('click',e=>{const a=el.dataset.e2Action;if(a==='left'){s.direction=DIRS[(DIRS.indexOf(s.direction)+3)%4];render()}else if(a==='right'){s.direction=DIRS[(DIRS.indexOf(s.direction)+1)%4];render()}else if(a==='close'){if(e.target.classList.contains('e2-modal-bg')||el.tagName==='BUTTON'){s.modal=null;render()}}else if(a==='close-clear'){s.modal=null;render()}else if(a==='menu'){if(s.flags.managementSheet)s.modal='sheet';else say('閲覧できる記録はまだない。');render()}}));app.querySelectorAll('[data-e2-interact]').forEach(el=>el.addEventListener('click',()=>interact(el.dataset.e2Interact)));app.querySelectorAll('[data-e2-item]').forEach(el=>el.addEventListener('click',()=>{const id=el.dataset.e2Item;s.selected=s.selected===id?null:id;if(id==='management_sheet'&&s.selected===id)s.modal='sheet';render()}));app.querySelectorAll('[data-e2-key]').forEach(el=>el.addEventListener('click',()=>{const k=el.dataset.e2Key;if(k==='消')s.input='';else if(k==='決定')return submit();else if(s.input.length<(s.modal==='cabinet'?3:4))s.input+=k;render()}))}
function shouldTakeOver(){return app.classList.contains('screen-escaped')||(localStorage.getItem(SAVE_KEY)&&!app.classList.contains('screen-title'))}
let controlling=false;function takeOverIfNeeded(){if(controlling||!shouldTakeOver())return;controlling=true;s=localStorage.getItem(SAVE_KEY)?load():defaultState();s.active=true;render()}
const observer=new MutationObserver(()=>takeOverIfNeeded());observer.observe(app,{attributes:true,childList:true});takeOverIfNeeded();